### ISSUE TITLE
 Only AAD object ID is stored in the role field.

### ISSUE THREAD

**Issue by cold01water** [codelibs/fess-ds-office365#3]
As a result of onedrive crawling, the AAD object ID is stored in the role field. The search result is not displayed because the value does not match the logged-in user ID.

In addition, although the permissions were set in the data store settings, they are not reflected in the crawled results

Is this correct behavior? Are there any mistakes?

Fess Enviroment
-------------------
 - Fess: fess-13.4.1-1.noarch
 -  plugin: fess-ds-office365 13.4.1

Data Store setting
------------------------
 - name: onedrive
 - handler: OneDriveDataStore
 - paramater
    - tenant=***
    - client_id=***
    - client_secret=***
 - script
    - title=files.name
    - content=files.description + "\n" + files.contents
    - mimetype=files.mimetype
    - created=files.created
    - last_modified=files.last_modified
    - url=files.web_url
    - role=files.roles
 - permission
    - {group}group01

crowl result(Admin's search result)
----------------------------------------
* role field: 1********-****-*****-****-************

**** is AAD object ID.
Fields such as file name and URL are correct.

**Comment by marevol** [comment]
Did you configure Fess with Azure AD?
If you want to use Role Search, you need to do that.

**Comment by cold01water** [comment]
Yes, using Azure AD.

However, fess exists in an on-premises environment.
fess is connected to AD via 'secure ldap' of Azure AD domain service.

* LDAP URL: ldaps://example.com:636/
* BaseDN: OU=AADDC Users,DC=example,DC=com
* BindDN: user@example.onmicrosoft.com
* Password: realpassword
* UserDN: %s
* filter: (&(objectClass=user)(userPrincipalName=%s))
* memberof: memberof

It was possible to login to fess as an AD user.

**Comment by cold01water** [comment]
The audit log showed the following:

```
action:LOGIN    user:***@***.onmicrosoft.com        permissions:1***@***.onmicrosoft.com|2group01|2group02|1***@****.onmicrosoft.com ip:192.168.10.100        time:2019-11-28T04:26:53.342155Z
```

**Comment by marevol** [comment]
It's LDAP authentication.
Fess provides SSO with AzureAD by [AzureAdAuthenticator](https://github.com/codelibs/fess/blob/master/src/main/java/org/codelibs/fess/sso/aad/AzureAdAuthenticator.java), but the configuration might not be documented.
If you need supports, please contact [Commercial Support](http://www.n2sm.net/en/support/fess_support.html).

**Comment by cold01water** [comment]
Thank you! That hint was enough.I solved it by reading your blog post.
