### ISSUE TITLE
Are some parameters implemented?

### ISSUE THREAD

**Issue by cold01water** [codelibs/fess-ds-office365#4]
Thank you for the information provided the other day.

Now, it is a question about the contents that are not described in the document.

In the source code, include_pattern and exclude_pattern parameters are defined. Is this parameter available?

When I try to set include_pattern, all URLs don't match.
When the debug log is output, the filter appears to be NULL as shown below.

```
DEBUG urlFilter: UrlFilterImpl [urlPattern=^(.*:/+)([^/]*)(.*)$, includeFilteringPattern=null, excludeFilteringPattern=null, cachedIncludeSet=[], cachedExcludeSet=[], sessionId=_s36yW4B_gFHX_XqoS7M-1, urlFilterService=org.codelibs.fess.crawler.service.impl.EsUrlFilterService@bbc855a]
```

I added the following debugging as a test.

```java:OneDriveDataStore.java
   # OneDriveDataStore.java
    protected UrlFilter getUrlFilter(final Map<String, String> paramMap) {
        final UrlFilter urlFilter = ComponentUtil.getComponent(UrlFilter.class);
        final String include = paramMap.get(INCLUDE_PATTERN);
        if (StringUtil.isNotBlank(include)) {
            urlFilter.addInclude(include);
            if (logger.isDebugEnabled()) {
                logger.debug("url include: {}", include);
                # addline
                logger.debug("mylog: {}", urlFilter);
            }
        }
```

As a result, ". *" Was entered in cachedIncludeSet.
Subsequent init processing appears to have lost the value.

```
 DEBUG mylog: UrlFilterImpl [urlPattern=^(.*:/+)([^/]*)(.*)$, includeFilteringPattern=null, excludeFilteringPattern=null, cachedIncludeSet=[".*"], cachedExcludeSet=[], sessionId=null, urlFilterService=null]
```

It would be helpful if you could get just a hint.

**Comment by deka0106** [comment]
Sorry for the late reply.

Maybe your output examples are the normal operations.

If `urlFilter.addInclude(pattern)` called before `urlFilter.init()`, `pattern` is cached on `urlFilter`.
https://github.com/codelibs/fess-crawler/blob/master/fess-crawler/src/main/java/org/codelibs/fess/crawler/filter/impl/UrlFilterImpl.java#L97

And after `urlFilter.init()` called, it is added to `urlFilterService`.
https://github.com/codelibs/fess-crawler/blob/master/fess-crawler/src/main/java/org/codelibs/fess/crawler/filter/impl/UrlFilterImpl.java#L135

So, I don't know what kind of problem is happening.
Could you give me what you set as `include_pattern` and what URLs are not matched?
