### ISSUE TITLE
Is it possible to crawl SharePoint Online site?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [codelibs/fess-ds-office365#9]
Thank you very much for the plugin. 

Is it possible to crawl SharePoint Online or Microsoft Stream site using it?

**Comment by marevol** [comment]
Please see https://github.com/codelibs/fess-ds-sharepoint

**Comment by rajasekhar-gundala** [comment]
> Please see https://github.com/codelibs/fess-ds-sharepoint

Thanks for the reply. I found the below steps for OneDrive. Is it possible to use the same kind of settings for SharePoint Online? I mean how to modify it to make it compatible with the SharePoint site. 

## OneDrive

title=files.name 
content=files.description + "\n" + files.contents
mimetype=files.mimetype
created=files.created
last_modified=files.last_modified
url=files.web_url
role=files.roles
